---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: "{{ $.Values.odf.catalogSource.name }}"
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  sourceType: grpc
  image: >-
    {{ $.Values.odf.catalogSource.image }}:{{ $.Values.odf.catalogSource.imageTag }}
  displayName: "Red Hat OpenShift Data Foundations Snapshot"
  publisher: "Red Hat AgnosticD"
