---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: "{{ $.Values.odf.catalogSource.name }}"
  namespace: openshift-storage
spec:
  sourceType: grpc
  image: >-
    {{ $.Values.odf.catalogSource.image }}:{{ $.Values.odf.catalogSource.tag }}
  displayName: "Red Hat OpenShift Data Foundations Snapshot"
  publisher: "Red Hat AgnosticD"
