---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: ocs-storagecluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  storageDeviceSets:
  - name: ocs-deviceset
    count: 1
    replica: 3
    dataPVCTemplate:
      spec:
        storageClassName: {{ $.Values.odf.storageCluster.cephStorage.className }}
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: {{ $.Values.odf.storageCluster.cephStorage.osdSize }}
    portable: true
