kind: ConfigMap
metadata:
  name:  cm-init-registry
  annotations:
    argocd.argoproj.io/sync-wave: "2"
apiVersion: v1
data:
  init_registry.sh: |
    yum install -y jq
    RESULT=$?
    if [ $RESULT -ne 0 ];
    then
        exit $RESULT
    fi
    ENDPOINT=$(oc get quayregistry quay -n quay-enterprise -o json | jq '.status.registryEndpoint' | sed 's/"//g')
    STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $ENDPOINT/api/v1/discovery)
    while [ $STATUS_CODE -ne 200 ] && [ $STATUS_CODE -ne 403 ]; do
        sleep 5s
        echo $STATUS_CODE
        echo $ENDPOINT
        ENDPOINT=$(oc get quayregistry quay -n quay-enterprise -o json | jq '.status.registryEndpoint' | sed 's/"//g')
        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $ENDPOINT/api/v1/discovery)
    done
    curl -X POST $ENDPOINT/api/v1/user/initialize -H "Content-Type: application/json" -d '{"username": "{{ $.Values.quay.registry.username }}", "password": "{{ $.Values.quay.registry.password }}", "email":"quayadmin@opentlc.com","access_token":"true"}'
