kind: ConfigMap
metadata:
  name:  init-config-bundle
apiVersion: v1
data:
  init_registry.sh: |
    yum install -y jq
    RESULT=$?
    if [ $RESULT -ne 0 ];
    then
        exit $RESULT
    fi

    oc get quayregistry quay
    if [ $RESULT -ne 0 ];
    then
        exit $RESULT
    fi

    APPS_DOMAIN=$(oc get ingress.config.openshift.io cluster -o json | jq '.spec.domain' | sed 's/\"//g')
    echo $'REGISTRY_TITLE: Red Hat Product Demo System Quay\nSERVER_HOSTNAME: quay.$APPS_DOMAIN\nEXTERNAL_TLS_TERMINATION: true\nSUPER_USERS:\n- quayadmin\nFEATURE_USER_INITIALIZE: true' | sed 's/\$APPS_DOMAIN/'"${APPS_DOMAIN}"'/g' > /tmp/config.yaml
    oc create secret generic config-bundle --from-file=config.yaml=/tmp/config.yaml