apiVersion: batch/v1
kind: Job
metadata:
  name: config-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
      - name: config-bundle
        command:
            - /bin/bash
            - -c
            - |
              sh /init-config-bundle/init_config_bundle.sh
        image: registry.redhat.io/openshift4/ose-cli:v4.7
        volumeMounts:
          - mountPath: /init-config-bundle
            name: init-config-bundle-volume
      restartPolicy: Never
      serviceAccount: default
      volumes:
      - name: init-config-bundle-volume
        configMap:
          name: init-config-bundle