apiVersion: batch/v1
kind: Job
metadata:
  name: init-registry
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
      - name: config-bundle
        command:
            - /bin/bash
            - -c
            - |
              sh /init-registry/init_registry.sh
        image: registry.redhat.io/openshift4/ose-cli:v4.7
        volumeMounts:
          - mountPath: /init-registry
            name: init-registry-volume
      restartPolicy: Never
      serviceAccount: default
      volumes:
      - name: init-registry-volume
        configMap:
          name: cm-init-registry