apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: {{ $.Values.quay.registry.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  configBundleSecret: config-bundle
  components:
  - kind: postgres
    managed: true
  - kind: objectstorage
    managed: true
  - kind: redis
    managed: true
  - kind: tls
    managed: true
  - kind: route
    managed: true
  - kind: quay
    managed: true
  - kind: clair
    managed: {{ $.Values.quay.registry.clair.enabled }}
  - kind: horizontalpodautoscaler
    managed: {{ $.Values.quay.registry.hpa.enabled }}
  - kind: mirror
    managed: {{ $.Values.quay.registry.mirror.enabled }}
  - kind: monitoring
    managed: {{ $.Values.quay.registry.monitoring.enabled }}
  - kind: clairpostgres
    managed: {{ $.Values.quay.registry.clairpostgres.enabled }}