apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: openshift-operators
spec:
  channel: "{{ $.Values.quay.channel  }}"
  installPlanApproval: Automatic
  name: quay-operator
  source: "{{ $.Values.quay.catalogSource.name }}"
  sourceNamespace: openshift-operators