kind: ConfigMap
metadata:
  name:  cm-set-admin-password
  annotations:
    argocd.argoproj.io/sync-wave: "3"
apiVersion: v1
data:
  set-admin-password.sh: |
    yum install -y jq
    RESULT=$?
    if [ $RESULT -ne 0 ];
    then
        exit $RESULT
    fi

    ADMIN_PASSWORD={{ $.Values.argocd.adminPassword }}
    if [ -z "$ADMIN_PASSWORD" ];
    then
        exit 0
    fi

    ARGOCD_SECRET=$(oc get secret openshift-gitops-cluster -n openshift-gitops -o json | jq '.data."admin.password"' | sed 's/"//g')
    while [ -z "$ARGOCD_SECRET" ]; do
        sleep 5s
        ARGOCD_SECRET=$(oc get secret openshift-gitops-cluster -n openshift-gitops -o json | jq '.data."admin.password"' | sed 's/"//g')
    done
    oc patch secret openshift-gitops-cluster --patch '{"stringData": {"admin.password": "'$ADMIN_PASSWORD'"}}' -n openshift-gitops