kind: ConfigMap
metadata:
  name:  cm-configure-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
apiVersion: v1
data:
  configure-argocd.sh: |
    yum install -y jq
    RESULT=$?
    if [ $RESULT -ne 0 ];
    then
        exit $RESULT
    fi

    APP_SYNC={{ $.Values.argocd.appSync }}
    if [ -z "$APP_SYNC" ];
    then
        exit 0
    fi

    oc patch ArgoCD openshift-gitops --type merge --patch '{"spec": {"controller": {"appSync": "'$APP_SYNC'"}}}' -n openshift-gitops
    while [ $? -ne 0 ]; do
        sleep 5s
        oc patch ArgoCD openshift-gitops --type merge --patch '{"spec": {"controller": {"appSync": "'$APP_SYNC'"}}}' -n openshift-gitops
    done
