apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: "{{ $.Values.argocd.catalogSource.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  sourceType: grpc
  image: >-
    {{ $.Values.argocd.catalogSource.image }}:{{ $.Values.argocd.catalogSource.imageTag }}
  displayName: "Openshift GitOps Catalog Source"
  publisher: "Red Hat AgnosticD"