apiVersion: batch/v1
kind: Job
metadata:
  name: set-admin-password
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: set-admin-password
        command:
            - /bin/bash
            - -c
            - |
              sh /set-admin-password/set-admin-password.sh
        image: registry.redhat.io/openshift4/ose-cli:v4.7
        volumeMounts:
          - mountPath: /set-admin-password
            name: set-admin-password-volume
      restartPolicy: Never
      serviceAccount: openshift-gitops-argocd-application-controller
      volumes:
      - name: set-admin-password-volume
        configMap:
          name: cm-set-admin-password