apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: "{{ $.Values.amqstreams.catalogSource.name }}"
spec:
  sourceType: grpc
  image: >-
    {{ $.Values.amqstreams.catalogSource.image }}:{{ $.Values.amqstreams.catalogSource.imageTag }}
  displayName: "AMQ Streams Catalog Source"
  publisher: "Red Hat AgnosticD"