---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-enterprise-og
  namespace: "{{ $.Values.quay.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
  - "{{ $.Values.quay.namespace }}"
