apiVersion: batch/v1
kind: Job
metadata:
  name: unseal-volt
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: "PostSync"
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
  namespace: vault
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
spec:
  template:
    spec:
      containers:
      - name: unseal-volt
        command:
            - /bin/bash
            - -c
            - |
              oc exec vault-0 --namespace=vault --stdin --tty -- vault operator init -format=yaml > /tmp/vault-auto-unseal-keys.txt
              cat /tmp/vault-auto-unseal-keys.txt | oc exec -i -n vault vault-0 -c vault "--" sh -c "cat > /vault/data/vault-auto-unseal-keys.txt"
              cat /vault-unseal-config/unseal.sh | oc exec -i -n vault vault-0 -c vault "--" sh -c "cat > /vault/data/unseal.sh"
              oc exec vault-0 --namespace=vault --stdin --tty -- /bin/sh /vault/data/unseal.sh
        image: registry.redhat.io/openshift4/ose-cli:v4.7
        volumeMounts:
          - mountPath: /vault-unseal-config
            name: vault-unseal-config-volume
      restartPolicy: Never
      serviceAccount: label-storage-nodes
      volumes:
      - name: vault-unseal-config-volume
        configMap:
          name: vault-unseal-config