apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sonarqube
      deploymentconfig: sonarqube
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarqube
        deploymentconfig: sonarqube
    spec:
      initContainers:
      - name: take-data-dir-ownership
        image: ubi8/ubi-minimal
        command: ["/bin/sh", "-c"]
        args:
          - mkdir -p /opt/sonarqube/data;
            chmod -R 777 /opt/sonarqube/data;
        volumeMounts:
        - name: sonar-data
          mountPath: /opt/sonarqube/data
      containers:
      - env:
        - name: JDBC_URL
          value: jdbc:postgresql://sonardb:5432/sonar
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://sonardb:5432/sonar
        - name: JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: sonardb
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: sonardb
        - name: SONAR_JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: sonardb
        - name: SONAR_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: sonardb
        - name: FORCE_AUTHENTICATION
          value: "false"
        - name: PROXY_HOST
        - name: PROXY_PORT
        - name: PROXY_USER
        - name: PROXY_PASSWORD
        - name: SONAR_SECURITY_REALM
        - name: LDAP_URL
        - name: LDAP_REALM
        - name: LDAP_AUTHENTICATION
        - name: LDAP_USER_BASEDN
        - name: LDAP_USER_REAL_NAME_ATTR
        - name: LDAP_USER_EMAIL_ATTR
        - name: LDAP_USER_REQUEST
        - name: LDAP_GROUP_BASEDN
        - name: LDAP_GROUP_REQUEST
        - name: LDAP_GROUP_ID_ATTR
        - name: LDAP_CONTEXTFACTORY
        - name: SONAR_AUTOCREATE_USERS
          value: "true"
        - name: LDAP_BINDDN
        - name: LDAP_BINDPASSWD
        image: {{ .Values.sonarqube.image }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: sonarqube
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/sonarqube/data
          name: sonar-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonarqube-data
