apiVersion: batch/v1
kind: Job
metadata:
  name: change-admin-password
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: change-admin-password
        command:
            - /bin/bash
            - -c
            - |
              sh /change-admin-password/change_admin_password.sh
        image: registry.redhat.io/openshift4/ose-cli:v4.7
        volumeMounts:
          - mountPath: /change-admin-password
            name: change-admin-password-volume
      restartPolicy: Never
      serviceAccount: default
      volumes:
      - name: change-admin-password-volume
        configMap:
          name: cm-change-admin-password