apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amqstreams
spec:
  channel: "{{ $.Values.amqstreams.channel }}"
  installPlanApproval: Automatic
  name: amqstreams-operator
  source: "{{ $.Values.amqstreams.catalogSource.name }}"
  sourceNamespace: openshift-operators