apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
spec:
  channel: "{{ $.Values.amqstreams.channel }}"
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: "{{ $.Values.amqstreams.catalogSource.name }}"
  sourceNamespace: openshift-operators