apiVersion: batch/v1
kind: Job
metadata:
  name: init-bundle
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: init-bundle
        command:
            - /bin/bash
            - -c
            - |
              sh /init-bundle/init_bundle.sh
        image: registry.redhat.io/openshift4/ose-cli:v4.7
        volumeMounts:
          - mountPath: /init-bundle
            name: init-bundle-volume
      restartPolicy: Never
      serviceAccount: default
      volumes:
      - name: init-bundle-volume
        configMap:
          name: cm-init-bundle