apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  namespace: "{{ $.Values.rhacsSecuredCluster.namespace }}"
  name: stackrox-secured-cluster-services
spec:
  clusterName: "{{ $.Values.rhacsSecuredCluster.name }}"
  auditLogs:
    collection: Auto
  admissionControl:
    listenOnUpdates: true
    bypass: BreakGlassAnnotation
    contactImageScanners: DoNotScanInline
    listenOnCreates: true
    timeoutSeconds: 3
    listenOnEvents: true
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints
  centralEndpoint: "{{ $.Values.rhacsSecuredCluster.centralEndpoint }}"
