---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: devspaecs-og
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
  - openshift-operators
